# Generated by Django 3.2.6 on 2021-08-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('alpha_code2', models.CharField(max_length=10)),
                ('capital', models.CharField(max_length=100)),
                ('population', models.CharField(max_length=100)),
                ('timezones', models.JSONField()),
                ('flag', models.URLField(blank=True, null=True)),
                ('languages', models.JSONField()),
                ('neighbouring_countries', models.JSONField()),
            ],
        ),
    ]
